apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-enterprise
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_ORG>/<YOUR_REPO>.git
    targetRevision: main
    path: redis-enterprise
  destination:
    server: https://kubernetes.default.svc
    namespace: rec1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
